name: Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Get version
        id: get_version
        run: yarn get:version

      - name: Display version
        run: |
          echo "Version: ${{ steps.get_version.outputs.version }}"
